### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by markjcasey** [tomaszbujnowicz/frontie-webpack#2]
Hi

Sorry to call this an "issues". I was just wondering if there was any documentation for this? It looks like a great boilerplate. I'm just curious how it works with bootstrap. For example, in _boostrap.grid.scss you state "The only change comparing to the original structure is that we don't import whole "variables.scss" from Bootstrap as we don't need all of them.". What if we wanted to include them all in a project? Can we add them to this file? Also, how would you recommend overriding the bootstrap variables?

Thanks!
Mark

**Comment by markjcasey** [comment]
Ah, I see. Yes, that makes sense. I think it is the ITCSS Methodology that confused me a little. I can see the benefits in using that process but it is probably a step beyond what I need for my project. I can work with this though, it's a great setup. Thanks :)

**Comment by tomaszbujnowicz** [comment]
Yes, this ITCSS methodology is optional so in case you want to use full Bootstrap, you can easily to do that. Thanks for your kind words, glad to hear that it works for you ;)
