### ISSUE TITLE
Proper way of including assets

### ISSUE THREAD

**Issue by iTuiTam** [tomaszbujnowicz/frontie-webpack#7]
Hello,

Thank you very much for your boilerplate project - it's almost perfect for my needs.

One question: what is the proper way of including assets (mainly images) in my layouts? 
`<img src="../../assets/img (...)` works okay during development `yarn start` but when I use `yarn build` to build website, all links are wrong and I need to replace them with `<img src="assets/img (...)`.

Thanks in advance.

**Comment by iTuiTam** [comment]
No idea why I was trying to use `../../` when `assets` was enough.

Sorry for troubling, and thanks again for wonderful starter.

**Comment by tomaszbujnowicz** [comment]
@iTuiTam Sorry, I didn't have time to reply this week but good to hear that you figured that out.
Many thanks for your kind words, appreciate it ;)
